### ISSUE TITLE
It doesn't work: "SecretKeyFactory not availalbe"

### ISSUE THREAD

**Issue by amossc** [codingharbour/kafka-docker-compose#4]
I followed the instructions but the broker fails to start.

What I did:
```
$ git clone
$ cd kafka-docker-compose/kafka-ssl
$ ./start-cluster.sh
```
Relevant logs from the broker:
```
broker  | [2021-07-01 01:31:04,833] WARN Failed to initialize a channel. Closing: [id: 0xb53fb32d] (io.netty.channel.ChannelInitializer)
broker  | org.apache.zookeeper.common.X509Exception$SSLContextException: Failed to create KeyManager
broker  | 	at org.apache.zookeeper.common.X509Util.createSSLContextAndOptions(X509Util.java:336)
broker  | 	at org.apache.zookeeper.common.X509Util.createSSLContext(X509Util.java:268)
broker  | 	at org.apache.zookeeper.ClientCnxnSocketNetty$ZKClientPipelineFactory.initSSL(ClientCnxnSocketNetty.java:454)
broker  | 	at org.apache.zookeeper.ClientCnxnSocketNetty$ZKClientPipelineFactory.initChannel(ClientCnxnSocketNetty.java:444)
broker  | 	at org.apache.zookeeper.ClientCnxnSocketNetty$ZKClientPipelineFactory.initChannel(ClientCnxnSocketNetty.java:429)
broker  | 	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
broker  | 	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
broker  | 	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
broker  | 	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
broker  | 	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
broker  | 	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
broker  | 	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
broker  | 	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
broker  | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502)
broker  | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
broker  | 	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
broker  | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
broker  | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
broker  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
broker  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
broker  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
broker  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
broker  | 	at java.base/java.lang.Thread.run(Thread.java:829)
broker  | Caused by: org.apache.zookeeper.common.X509Exception$KeyManagerException: java.security.NoSuchAlgorithmException: 1.2.840.113549.1.5.13 SecretKeyFactory not available
broker  | 	at org.apache.zookeeper.common.X509Util.createKeyManager(X509Util.java:417)
broker  | 	at org.apache.zookeeper.common.X509Util.createSSLContextAndOptions(X509Util.java:334)
broker  | 	... 22 more
broker  | Caused by: java.security.NoSuchAlgorithmException: 1.2.840.113549.1.5.13 SecretKeyFactory not available
broker  | 	at java.base/javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:122)
broker  | 	at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:168)
broker  | 	at org.apache.zookeeper.util.PemReader.loadPrivateKey(PemReader.java:164)
broker  | 	at org.apache.zookeeper.util.PemReader.loadPrivateKey(PemReader.java:149)
broker  | 	at org.apache.zookeeper.util.PemReader.loadKeyStore(PemReader.java:108)
broker  | 	at org.apache.zookeeper.common.PEMFileLoader.loadKeyStore(PEMFileLoader.java:49)
broker  | 	at org.apache.zookeeper.common.X509Util.createKeyManager(X509Util.java:406)
broker  | 	... 23 more
broker  | [2021-07-01 01:31:04,870] INFO future isn't success, cause: (org.apache.zookeeper.ClientCnxnSocketNetty)
broker  | io.netty.channel.StacklessClosedChannelException
broker  | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(ChannelPromise)(Unknown Source)
```

**Comment by chromy96** [comment]
Hi @amossc ,
thanks for reporting the issue. It looks like openssl didn't convert the broker's private key to a pkcs8 format for some reason.
Could you send me the version of the openssl you're using and could you also attach the generated private key? you can find it in the file `security/broker-keypair.pem`.
